[project]
name = "test-remote-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vikas Kasaudhan", email = "kasaudhanv036@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastmcp>=4.0.3",
]

[project.scripts]
test-remote-mcp-server = "test_remote_mcp_server:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
